#include <tc/tc_startup.h>
#include <epm/epm_toolkit_tc_utils.h>
#include <tc/emh.h>
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <tcinit/tcinit.h>
#include <tccore/item.h>
#include <tccore/aom.h>
#include <tccore/aom_prop.h>
#include <tccore/grm.h>
#include <cfm/cfm.h>
#include <bom/bom.h>
#include <ae/ae.h>
#include <ae/dataset.h>
#include <sa/tcvolume.h>
#include <sa/tcfile.h>
#include<string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <map>
#include <vector>
#include <fclasses/tc_string.h>
